name: palindrome
version: 0.1.0.0
github: "githubuser/palindrome"
license: BSD-3-Clause
author: "Rafail"
maintainer: "rafail.dev@gmail.com"
copyright: "2024 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/rafail-dev/will-kurt-haskelle>

dependencies:
  - base >= 4.7 && < 5
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings


library:
  source-dirs: src


executables:
  palindrome-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - palindrome
    # default-extensions: (to global)
    #   - OverloadedStrings

tests:
  palindrome-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - palindrome
    # default-extensions: (to global)
    #   - OverloadedStrings
